# Generated by Django 4.2.1 on 2023-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_delete_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
