# Generated by Django 4.2.1 on 2023-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calatog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpokemon',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
